#cloud-config
autoinstall:
  version: 1
    
  locale: en_US.UTF-8
  keyboard:
        layout: us
        variant:
  network:
        network:
            version: 2
            ethernets:
                enp0s25:
                   dhcp4: yes
                enp3s0: {}
                enp4s0: {}
            bonds:
                bond0:
                    dhcp4: yes
                    interfaces:
                        - enp3s0
                        - enp4s0
                    parameters:
                        mode: active-backup
                        primary: enp3s0      
  identity:
    hostname: custom-ubuntu
    username: michel
    password: $6$brNXMqMz1o8J852W$AJ3lIu1Vw9Piwlol2Y.ohEUcI85O5rhOO1AiskTiCOVFzKWn2v1k4GwPjiB7aCFbYvwew3S0Hhf.HU9uZfLvX1 
  storage:
    layout:
      name: lvm
  bootloader:
    install: true
    grub:
      timeout: 5
      cmdline: "quiet splash"
  user-data:
    disable_root: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDXoY8mMFKoXCPtZzpnyVABARscpaH5VKsjK0LOzoUvbElf9QMYYw7YA/QDk92MA7E5HLEGdX6R9NonoOyI9YABOg55wmVqfsGw05pnlrqtdTcI1Pt1ERzh7eMFK70+bRYsgyMJYLPiRLfB3dr3Ns4/q7PbsRRq8i6AX9BPtdTdzw== michelmougoue29@gmail.com
    snaps:  
        - name: go
          channel: 1.20/stable
          classic: true
  late-commands:
        - sed -ie 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=30/' /target/etc/default/grub     

